import tkinter as tk
root = tk.Tk()
root.title("MY GUI")
root.configure(bg="Pink")
menu1 = tk.Menu(root)
root.config(menu=menu1)
sub = tk.Menu(menu1)
btn1 = tk.Button(root,text = "FINYA TU USIOGOPE!")
btn1.pack(side="bottom")
menu1.add_cascade(label="Sign In",menu = sub)
menu1.add_cascade(label="Home",menu = sub)
menu1.add_cascade(label="Find",menu = sub)
sub.add_command(label = "File",command="")
sub.add_command(label = "Contact",command="")
sub.add_command(label = "About",command="")
sub2=tk.Menu(menu1)
menu1.add_cascade(label = "Edit",menu = sub2)
sub2.add_command(label = "Select",command ="")
sub2.add_command(label = "History",command ="")
sub3=tk.Menu(sub2)
sub2.add_cascade(label = "Print as",menu = sub3)
sub2.add_command(label = "New Data",command ="")
sub2.add_command(label = "3D",command ="")
sub3.add_command(label = "2D",command ="")
sub3.add_command(label = "1D",command ="")
sub3.add_separator()
sub3.add_command(label = "quit",command ="")
root.mainloop()
